{
    "docs": "https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/pylint.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/pylint.html)] failed with 1 error:", 
            "output": "plugins/modules/ix_command.py:132:4: ansible-bad-function: Call module.log or module.debug instead of builtins.print"
        }
    ], 
    "verified": false
}
